---
apiVersion: v1
kind: Service
metadata:
  name: javabot-backend-service
  annotations:
    oci.oraclecloud.com/loadbalancer-policy: IP_HASH
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: javabot-backend

---
apiVersion: v1
kind: Service
metadata:
  name: javabot-backend-router
spec:
  selector:
    app: javabot-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: http

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: javabot-backend-deployment
spec:
  selector:
    matchLabels:
      app: javabot-backend
  replicas: 2
  template:
    metadata:
      labels:
        app: javabot-backend
        version: v1
    spec:
      containers:
        - name: javabot-backend
          image: mx-queretaro-1.ocir.io/axgyv8vo90ix/orabot_registry/javabot-backend:0.1
          imagePullPolicy: Always
          env:
            - name: db_user
              value: APP_DATA
            - name: db_url
              value: jdbc:oracle:thin:@oraclebotdb_tp?TNS_ADMIN=/OracleBotProject/Oracle_Java_Bot/oracle
            - name: driver_class_name
              value: oracle.jdbc.OracleDriver
            - name: dbpassword
              value: verySafePassword123
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: credentials
              mountPath: /OracleBotProject/Oracle_Java_Bot/oracle
      restartPolicy: Always
      volumes:
        - name: credentials
          secret:
            secretName: oracle-db-secret
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              app: javabot-backend
