spring:
  datasource:
    driver_class_name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@oraclebotdb_high?TNS_ADMIN=/Users/GeekD/Downloads/OrabotWallet
    username: ADMIN
    password: Aristogatos1803@@@
  jpa:
    database: ORACLE
    database-platform: org.hibernate.dialect.Oracle12cDialect
    hibernate:
      ddl-auto: none
    show-sql: true
  security:
    user:
      name: ADMIN # Change for variable (STATE)
      password: Aristogatos1803@@@ # Change for variables (STATE)