spring:
  datasource:
    driver_class_name: oracle.jdbc.OracleDriver
    password: 2zeCj8wVC3AKXIf
    url: jdbc:oracle:thin:@petertestdb_medium?TNS_ADMIN=/Users/psong/Downloads/Wallet_petertestDB
    username: app_data
  jpa:
    database: ORACLE
    database-platform: org.hibernate.dialect.Oracle12cDialect
    hibernate:
      ddl-auto: none
    show-sql: true
  security:
    user:
      name: ${ui_username}
      password: ${ui_password}